# Generated by Django 4.1 on 2023-02-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenfication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
    ]
