# Generated by Django 4.1 on 2023-02-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
