# Generated by Django 4.1 on 2023-02-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0007_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
