# Generated by Django 4.1 on 2023-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0009_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='Nom non donnée', max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
