# Generated by Django 4.1 on 2023-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Rendez_Vous', '0002_appointment_delete_rdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='subject',
            new_name='text',
        ),
    ]
