# Generated by Django 4.1 on 2023-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Rendez_Vous', '0003_rename_subject_appointment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='time_debut',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_fin',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
